const images = {
  backArrow: require("./back-arrow.png"),
  appIcon: require("./app-icon.png"),
  premium: require("./premium.png"),
  help: require("./help.png"),
  random: require("./random.png"),
  correctWord: require("./correct-word.png"),
  timer: require("./timer.png"),
  home: require("./home.png"),
  timeOver: require("./time-over.png"),
  whistle: require("./whistle.png"),
  correct: require("./correct.png"),
  repeat: require("./repeat.png"),
  wrong: require("./wrong.png"),
  gameOver: require("./game-over.png"),
  playAgain: require("./play-again.png"),
  privacyPolicy: require("./privacy-policy.png"),
  rating: require("./rating.png"),
  share: require("./share.png"),
  soundOff: require("./sound-off.png"),
  soundOnBlack: require("./sound-on-black.png"),
  soundOnWhite: require("./sound-on-white.png"),
  icon: require("./icon.png"),
  easy: require("./easy.png"),
  hard: require("./hard.png"),
  letsPlayPrimary: require("./lets-play-primary.png"),
  letsPlayWhite: require("./lets-play-white.png"),
  settings: require("./settings.png"),
  contactUs: require("./contact-us.png"),
  mood1: require("./mood-1.png"),
  mood2: require("./mood-2.png"),
  mood3: require("./mood-3.png"),
  mood4: require("./mood-4.png"),
  mood5: require("./mood-5.png"),
  feedback: require("./feedback.png"),
  language: require("./language.png"),
  categories : require("./menu.png")
};

export default images;
